text:
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your [social_comment:commented_entity_link_html]</p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your [social_comment:commented_entity_link_html]</p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your [social_comment:commented_entity_link_html]</p>'
    format: full_html
