text:
  -
    format: full_html
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> replied on your <a href=\"[message:field_message_related_object:entity:url:absolute]\">comment</a> in [social_comment:commented_entity_link_html]</p>\r\n"
  -
    format: full_html
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> replied on your <a href=\"[message:field_message_related_object:entity:url:absolute]\">comment</a> in [social_comment:commented_entity_link_html]</p>\r\n"
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> replied on your <a href="[message:field_message_related_object:entity:url:absolute]">comment</a> in [social_comment:commented_entity_link_html]</p>'
