label: 'Nyeste grupper'
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Første'
            last: 'Siste »'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      fields:
        label:
          separator: ', '
      title: 'Alle grupper'
  block_newest_groups:
    display_options:
      title: 'Nyeste grupper'
      use_more_text: 'Alle grupper'
