label: Aktivitetsstrøm
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      title: Strøm
  page_activity_stream:
    display_title: Side
  page_explore:
    display_options:
      title: 'Se aktivitet'
