display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Neste ›'
            first: '« Første'
            last: 'Siste »'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      fields:
        status:
          separator: ', '
      title: Search
      empty:
        area:
          content:
            value: 'Ingen resultater funnet.'
      arguments:
        search_api_fulltext:
          exception:
            title: Alle
  page:
    display_title: Side
