label: 'Siste emner'
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      fields:
        title:
          separator: ', '
      title: 'Alle emner'
  block_latest_topics:
    display_options:
      title: 'Nyeste emner'
      use_more_text: 'Alle emner'
  group_topics_block:
    display_options:
      block_description: 'Siste emner for gruppa'
      empty:
        area_text_custom:
          content: 'Ingen emner i denne gruppa'
      arguments:
        gid:
          exception:
            title: Alle
      title: 'Nyeste emner'
      use_more_text: 'Alle emner'
  page_latest_topics:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Neste ›'
            first: '« Første'
            last: 'Siste »'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
