label: 'Hendelser i gruppa'
display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
          tags:
            previous: ‹‹
            next: ››
      fields:
        label:
          separator: ', '
      filters:
        field_event_date_value:
          group_info:
            label: 'Status for hendelse'
            group_items:
              1:
                title: 'Kommende hendelser'
              2:
                title: 'Hendelser som har startet eller er ferdige'
      title: 'Hendelser i gruppa'
      empty:
        area_text_custom:
          content: 'Ingen hendelser i denne gruppa'
      arguments:
        gid:
          exception:
            title: Alle
  page_group_events:
    display_title: Side
