display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      fields:
        label:
          separator: ', '
      title: 'Om gruppa'
      arguments:
        id:
          exception:
            title: Alle
          title: 'Om {{ arguments.id }}'
  page_group_about:
    display_title: Side
