preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: vertical
icon_default: true
icon_path: ''
_core:
  default_config_hash: n_qpss6W5gVA3e38uErsrMTfKQDnBNhmW2U9qPl9b5w
langcode: nb
