preset_accent_color: custom
preset_focus_color: custom
enable_darkmode: false
classic_toolbar: vertical
icon_default: true
icon_path: ''
_core:
  default_config_hash: n_qpss6W5gVA3e38uErsrMTfKQDnBNhmW2U9qPl9b5w
langcode: nb
accent_color: '#29abe2'
focus_color: '#1f80aa'
favicon:
  use_default: false
  path: themes/contrib/socialblue/favicon.ico
  mimetype: image/vnd.microsoft.icon
secondary_toolbar_frontend: false
