usage_data_enabled: 0
usage_data:
  website_url: website_url
  entity_type_count: entity_type_count
  open_social_version: open_social_version
  system_data: system_data
  modules_installed: modules_installed
refresh_interval: 86400
url: 'https://connect.getopensocial.com/usage'
_core:
  default_config_hash: kYujB5MHv3f8GgMbxKRFJ84hk9ZnZjsp0GVagg878s0
langcode: nb
