font_primary: Montserrat
color_primary: '#29abe2'
color_secondary: '#1f80aa'
color_accents: '#ffc142'
border_radius: '10'
_core:
  default_config_hash: IlUCYWV3hnjfghFlkuR8OlqQwBgOiOqTMZ5TniqJnqs
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://www.drupalnorge.no/profiles/contrib/social/themes/socialblue/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: false
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  socialbase: 8000
  socialblue: 8000
langcode: nb
