settings:
  allowed_values:
    -
      label: Community
      description: 'Visible only to members who are logged in'
    -
      label: Public
      description: 'Visible to all visitors of the site'
    -
      label: Community
      description: 'Visible only to members who are logged in'
