label: 'Join to group'
description: 'A person joins a group I am managing'
text:
  -
    value: '<p><a href="[message:recipient-user:url:absolute]">[message:recipient-user:display-name]</a> joined the <a href="[message:gurl]">[message:gtitle]</a> group</p>'
  -
    value: '<p><a href="[message:recipient-user:url:absolute]">[message:recipient-user:display-name]</a> joined the <a href="[message:gurl]">[message:gtitle]</a> group</p>'
  -
    value: '<p><a href="[message:recipient-user:url:absolute]">[message:recipient-user:display-name]</a> joined the <a href="[message:gurl]">[message:gtitle]</a> group</p>'
