label: 'Create post on profile stream output'
description: 'A person created a post on my profile and I see it on the stream'
text:
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> &gt; <a href=\"[message:recipient-user-url]\">[activity:field_activity_recipient_user_display_name]</a></p>\n"
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> posted on your profile</p>\n"
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> posted on your <a href="[message:recipient-user-url]">profile</a></p>'
