label: 'Create comment on post on my profile'
description: 'A person commented on a post on my profile'
text:
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> commented on a post on your <a href=\"[message:recipient-user-url]\">profile</a></p>\n"
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> commented on a post on your <a href=\"[message:recipient-user-url]\">profile</a></p>\n"
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on a post on your <a href="[message:recipient-user-url]">profile</a></p>'
