label: 'Add or edit a Search API index'
tips:
  search-api-index-form-introduction:
    label: 'Adding or editing an index'
    body: 'This form can be used to edit an existing index or add a new index to your site. Indexes define a set of data that will be indexed and can then be searched.'
  search-api-index-form-name:
    label: 'Index name'
    body: 'Enter a name to identify this index. For example, "Content index". This will only be displayed in the admin user interface.'
  search-api-index-form-datasources:
    label: Datasources
    body: 'Datasources define the types of items that will be indexed in this index. By default, all content entities (like content, comments and taxonomy terms) will be available here, but modules can also add their own.'
  search-api-index-form-tracker:
    label: Tracker
    body: 'An index''s tracker is the system that keeps track of which items there are available for the index, and which of them still need to be indexed. Changing the tracker of an existing index will lead to reindexing of all items.'
  search-api-index-form-server:
    label: Server
    body: 'The search server that the index should use for indexing and searching. If no server is selected here, the index cannot be enabled. An index can only have one server, but a server can have any number of indexes.'
  search-api-index-form-description:
    label: 'Index description'
    body: 'Optionally, enter a description to explain the function of the index in more detail. This will only be displayed in the admin user interface.'
  search-api-index-form-options:
    label: 'Advanced options'
    body: 'These options allow more detailed configuration of index behavior, but can usually safely be ignored by inexperienced users.'
