label: 'Advanced Queue jobs'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        job_id:
          label: 'Job ID'
        num_retries:
          alter:
            text: 'Number of retries: {{ num_retries }}'
          format_plural_string: !!binary MQNAY291bnQ=
        state:
          label: State
          alter:
            text: "{{ state }}\n\n{{ num_retries }}"
        type:
          label: 'Job type'
        payload:
          label: Payload
          alter:
            text: '<pre>{{ payload }}</pre>'
        available:
          label: 'Available date'
        processed:
          label: 'Processed date'
          alter:
            text: "{{ processed }}\n\n{{ message }}"
        message:
          label: Message
          alter:
            text: 'Message: {{ message }}'
        operations:
          label: Operations
      filters:
        type:
          expose:
            label: 'Job type'
        state:
          expose:
            label: State
        available:
          expose:
            label: 'Available from'
            placeholder: YYYY-MM-DD
          group_info:
            label: 'Available date'
      title: Jobs
      empty:
        area_text_custom:
          content: 'No jobs found'
      arguments:
        queue_id:
          exception:
            title: All
  page_1:
    display_title: Page
