label: 'Content I follow'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: Type
          separator: ', '
        link_flag:
          label: Operations
          alter:
            text: '<div class="btn btn-sm"> {{ link_flag }} </div>'
      filters:
        type:
          expose:
            label: 'Content type'
      sorts:
        created_1:
          admin_label: sort_flag_created
      title: 'Content I follow'
      arguments:
        uid:
          admin_label: 'Current User'
          exception:
            title: All
  following:
    display_title: Page
