display:
  default:
    display_options:
      filters:
        id:
          group_info:
            label: ID
          expose:
            label: Group
        combine:
          expose:
            label: 'Name or email contains'
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Active
              2:
                title: Blocked
        created:
          expose:
            label: 'Registration date'
        login:
          expose:
            label: 'Last login'
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        views_bulk_operations_bulk_form:
          label: 'Bulk action'
        name:
          label: Username
        status:
          label: Status
          settings:
            format_custom_true: Active
            format_custom_false: Blocked
        roles_target_id:
          label: Roles
        created:
          label: 'Member for'
          settings:
            future_format: '@interval'
            past_format: '@interval'
        access:
          label: 'Last access'
          settings:
            future_format: '@interval hence'
            past_format: '@interval ago'
        operations:
          label: Operations
        mail:
          separator: ', '
        field_profile_first_name:
          label: 'First name'
          separator: ', '
        field_profile_last_name:
          label: 'Last name'
          separator: ', '
      title: People
      empty:
        area_text_custom:
          content: 'No people available.'
      use_more_text: more
    display_title: Master
  page_1:
    display_title: Page
    display_options:
      menu:
        title: List
        description: 'Find and manage people interacting with your site.'
      tab_options:
        title: People
        description: 'Manage user accounts, roles, and permissions.'
label: People
description: 'Find and manage people interacting with your site.'
