<?php

/**
 * @file
 * Drupal Norge custom module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function drupalnorge_custom_entity_insert(EntityInterface $entity) {
  $type = $entity->getEntityTypeId();
  /** @var \Drupal\slack\Slack $slack */
  $slack = \Drupal::service('slack.slack_service');
  if ($type == 'comment') {
    /** @var \Drupal\comment\Entity\Comment $entity */
    $owner = $entity->getOwner();
    $node = $entity->getCommentedEntity();
    $slack->sendMessage(t('@user commented on @title: @url', [
      '@user' => $owner->getDisplayName(),
      '@title' => $node->label(),
      '@url' => $node->toUrl('canonical', [
        'absolute' => TRUE,
      ])->toString(),
    ]));
  }
  if ($type == 'node') {
    /** @var \Drupal\node\Entity\Node $entity */
    $slack->sendMessage(t('@user posted on drupalnorge.no: @title. @url', [
      '@title' => $entity->label(),
      '@user' => $entity->getOwner()->getDisplayName(),
      '@url' => $entity->toUrl('canonical', [
        'absolute' => TRUE,
      ])->toString(),
    ]));
  }
}

/**
 * Implements hook_file_download().
 */
function drupalnorge_custom_file_download($uri) {
  if ($uri == 'private://default_images/default-profile-picture.png') {
    // Stole this from file_download().
    $files = \Drupal::entityManager()->getStorage('file')->loadByProperties([
      'uri' => $uri,
    ]);
    if (count($files)) {
      foreach ($files as $item) {
        // Since some database servers sometimes use a case-insensitive
        // comparison by default, double check that the filename is an exact
        // match.
        if ($item->getFileUri() === $uri) {
          $file = $item;
          break;
        }
      }
    }
    if (!isset($file)) {
      return;
    }
    $headers = file_get_content_headers($file);
    return $headers;
  }
}
